In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.DataFrame(np.random.randn(3,4), index = list('abc'), columns=['olma', 'anor', 'anjir', 'qovun'])
df

       olma      anor     anjir     qovun
a -0.547896 -0.917078 -0.236400 -0.663767
b -0.817360  1.754059  0.274299  1.739159
c  0.009943 -0.506086 -0.950010  0.602209

In [8]:
#Faqat musbat qiymat olish uchun
np.abs(df)

       olma      anor     anjir     qovun
a  0.547896  0.917078  0.236400  0.663767
b  0.817360  1.754059  0.274299  1.739159
c  0.009943  0.506086  0.950010  0.602209

In [9]:
np.round(df)

   olma  anor  anjir  qovun
a  -1.0  -1.0   -0.0   -1.0
b  -1.0   2.0    0.0    2.0
c   0.0  -1.0   -1.0    1.0

In [11]:
df.mean()

olma    -0.451771
anor     0.110298
anjir   -0.304037
qovun    0.559200
dtype: float64

In [12]:
df.mean(axis=1)

a   -0.591285
b    0.737539
c   -0.210986
dtype: float64

In [13]:
df.apply(sum)

olma    -1.355312
anor     0.330895
anjir   -0.912111
qovun    1.677601
dtype: float64

In [14]:
f = lambda x: x.max() - x.min()

In [15]:
df.apply(f)

olma     0.827303
anor     2.671136
anjir    1.224308
qovun    2.402926
dtype: float64

In [16]:
def foo(x):
  return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [17]:
df.apply(foo)

         olma      anor     anjir     qovun
min -0.817360 -0.917078 -0.950010 -0.663767
max  0.009943  1.754059  0.274299  1.739159

In [18]:
df1 = pd.DataFrame(np.arange(1, 13).reshape(3, 4), index=list('abc'), columns=['olma', 'anor', 'anjir', 'qovun'])
df1

   olma  anor  anjir  qovun
a     1     2      3      4
b     5     6      7      8
c     9    10     11     12

In [19]:
lambda x: x*x

In [20]:
df1.applymap(lambda x: x*x)

/tmp/ipykernel_997/4023462903.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda x: x*x)

   olma  anor  anjir  qovun
a     1     4      9     16
b    25    36     49     64
c    81   100    121    144