In [1]:
import pandas as pd

In [2]:
import numpy as np

In [5]:
emails = {"botir" : "botir123@gmail.com", "nurbek":"nurbek456@gmail.ru", "ali": "ali789@gmail.uz", "baxrom":"baxrom12@gmail.com"}
usurnames = {"botir" : "botirov", "nurbek":"nurbekov", "ali": "aliyev", "baxrom":"baxromov"}

data = {
    "username" : usurnames,
    "email" : emails
}

In [7]:
df = pd.DataFrame(data)

In [8]:
df

        username               email
botir    botirov  botir123@gmail.com
nurbek  nurbekov  nurbek456@gmail.ru
ali       aliyev     ali789@gmail.uz
baxrom  baxromov  baxrom12@gmail.com

In [9]:
df.index

Index(['botir', 'nurbek', 'ali', 'baxrom'], dtype='object')

In [14]:
data2 = {
    "username" : {"davlat":"davlatbek", "umid":"umidjon", "shahzod":"shakh"},
    "email" : {"davlat":"davlat@gmail.com","umid": "umid@gmail.com","shahzod": "shahzod@gmail.com"}
}

In [15]:
data2

{'username': {'davlat': 'davlatbek', 'umid': 'umidjon', 'shahzod': 'shakh'},
 'email': {'davlat': 'davlat@gmail.com',
  'umid': 'umid@gmail.com',
  'shahzod': 'shahzod@gmail.com'}}

In [16]:
df2 = pd.DataFrame(data2)
df2

          username              email
davlat   davlatbek   davlat@gmail.com
umid       umidjon     umid@gmail.com
shahzod      shakh  shahzod@gmail.com

In [21]:
df3 = pd.concat([df, df2])
df3

          username               email
botir      botirov  botir123@gmail.com
nurbek    nurbekov  nurbek456@gmail.ru
ali         aliyev     ali789@gmail.uz
baxrom    baxromov  baxrom12@gmail.com
davlat   davlatbek    davlat@gmail.com
umid       umidjon      umid@gmail.com
shahzod      shakh   shahzod@gmail.com

In [22]:
newind = pd.Index(["botir", "abc", "dfg"])
newind

Index(['botir', 'abc', 'dfg'], dtype='object')

In [23]:
newind.isin(df3.index)

array([ True, False, False])

In [24]:
df3.index.difference(newind)

Index(['ali', 'baxrom', 'davlat', 'nurbek', 'shahzod', 'umid'], dtype='object')

In [25]:
newind.difference(df3.index)

Index(['abc', 'dfg'], dtype='object')

In [26]:
df3.index.union(newind)

Index(['abc', 'ali', 'baxrom', 'botir', 'davlat', 'dfg', 'nurbek', 'shahzod',
       'umid'],
      dtype='object')