In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("https://raw.github.com/anvarnarz/praktikum_datasets/main/merc.csv")
df.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
1,S Class,2017,34948,Automatic,27000,Hybrid,20,61.4,2.1
2,SL CLASS,2016,49948,Automatic,6200,Petrol,555,28.0,5.5
3,G Class,2016,61948,Automatic,16000,Petrol,325,30.4,4.0
4,G Class,2016,73948,Automatic,4000,Petrol,325,30.1,4.0

In [3]:
data = {
    "age" : [10, 20, 30, 40, 50, 60],
    "year" : [2016, 2006, 1996, 1986, 1976, 1966]
}

obj = pd.DataFrame(data)
obj

   age  year
0   10  2016
1   20  2006
2   30  1996
3   40  1986
4   50  1976
5   60  1966

In [4]:
obj['age'].corr(obj['year'])

np.float64(-0.9999999999999998)

In [5]:
df['year'].corr(df['mileage'])

np.float64(-0.7380268515364232)

In [6]:
df['price'].corr(df['year'])

np.float64(0.5207118525518949)

In [7]:
df['price'].corr(df['mileage'])

np.float64(-0.537214124104646)

In [9]:
df.corr(numeric_only=True)

                year     price   mileage       tax       mpg  engineSize
year        1.000000  0.520712 -0.738027  0.012480 -0.094626   -0.142147
price       0.520712  1.000000 -0.537214  0.268717 -0.438445    0.516126
mileage    -0.738027 -0.537214  1.000000 -0.160223  0.202850    0.063652
tax         0.012480  0.268717 -0.160223  1.000000 -0.513742    0.338341
mpg        -0.094626 -0.438445  0.202850 -0.513742  1.000000   -0.339862
engineSize -0.142147  0.516126  0.063652  0.338341 -0.339862    1.000000

In [11]:
df.corrwith(df['price'], numeric_only=True)

year          0.520712
price         1.000000
mileage      -0.537214
tax           0.268717
mpg          -0.438445
engineSize    0.516126
dtype: float64